services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xenova_db
    ports:
      - "5433:5432"
    volumes:
      - xenova_postgres_data:/var/lib/postgresql/data

  api-service:
    build:
      context: .
      dockerfile: apps/api-service/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./apps/api-service/.env
    depends_on:
      - redis
      - db

  engine-service:
    build:
      context: .
      dockerfile: apps/engine-service/Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./apps/engine-service/.env
    depends_on:
      - redis
      - db

  price-poller-service:
    build:
      context: .
      dockerfile: apps/price-poller-service/Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./apps/price-poller-service/.env
    depends_on:
      - redis

volumes:
  xenova_postgres_data:
